name: ignite_sol
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  json_annotation: 3.1.1
  rxdart: 0.25.0
  dio: 3.0.10
  shimmer: 1.1.2
  keyboard_visibility: 0.5.6
  url_launcher: 5.7.10
  fluttertoast: 7.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  json_serializable: 3.5.1
  build_runner: 1.10.2

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/json/

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: fonts/Montserrat-SemiBold.ttf
          weight: 600
